### ISSUE TITLE
Pillagers don't fire at the player with any weapon

### ISSUE THREAD

**Issue by AnxiousRexy** [SmileycorpMC/raids-backport#4] opened 2024-04-16 01:34 UTC

**Comment by SmileycorpMC** [comment] 2024-04-16 09:46
What mods do you have installed?

Them shooting has been working for me.

**Comment by AnxiousRexy** [comment] 2024-04-27 19:45
> What mods do you have installed?
> 
> Them shooting has been working for me.

I tried without mods, They do shoot. Idk why its like that tbh but my last crash report lists my mod list.

**Comment by Grizdor** [comment] 2024-05-01 19:25
I think I have the same issue.

- With only **Raids Backport 1.1.2** :
Pillagers shoot me like intended with the vanilla bow.

- With only **Raids Backport 1.1.2** and **Crossbows Backport 1.1.0b** :
Pillagers don't shoot me with their crossbows. But they still doing the charging crossbow animation continuously even if they don't shoot with it. If I let a pillager with a bow in the world before adding Crossbows Backport it don't shoot with the bow either.

**Comment by ZajiShinobi2** [comment] 2024-05-06 13:05
I have the same issue. But the problem is in the updated versions of this mod. In the 1.1.0 they shoot normally. Even if i have mods installed. Maybe that's a clue to fix the problem. Sorry if my english is bad.

**Comment by Carvercarver1** [comment] 2024-05-26 18:50
Same. Could it be something related to the AI or the lack of ammo or reload script not resulting it?

**Comment by SmileycorpMC** [comment] 2024-05-31 12:16
fixed in 1.1.3

**Closed by SmileycorpMC** 2024-05-31 12:16 UTC
